In [0]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [0]:
sel = [1,2,3,4,10,11,14,20,23,29,30,31,32,33,40,41,43,44]
r= pd.DataFrame()
with open('/content/gdrive/My Drive/ML/2016/On_Time_On_Time_Performance_2016_1/On_Time_On_Time_Performance_2016_1.csv', 'r') as f:
  r1= pd.read_csv(f,usecols = sel)
  r1['year']='2016'
  r=pd.concat([r,r1],axis=0,ignore_index=True)

In [0]:
for i in range(2,13):
  filename='/content/gdrive/My Drive/ML/2016/On_Time_On_Time_Performance_2016_'+str(i)+'/On_Time_On_Time_Performance_2016_'+str(i)+'.csv'
  with open(filename, 'r') as f:
    r1= pd.read_csv(f,usecols = sel)
    r1['year']='2016'
    r=pd.concat([r,r1],axis=0,ignore_index=True)

In [0]:
for i in range(1,13):
  filename='/content/gdrive/My Drive/ML/2017/On_Time_On_Time_Performance_2017_'+str(i)+'/On_Time_On_Time_Performance_2017_'+str(i)+'.csv'
  with open(filename, 'r') as f:
    r1= pd.read_csv(f,usecols = sel)
    r1['year']='2017'
    r=pd.concat([r,r1],axis=0,ignore_index=True)

In [0]:
def func(row):
    if row['DepTime'] %100!=0:
        k=row['DepTime']//100 + 1 if row['DepTime'] %100>30 else 0 
        return k
    else:
        return row['DepTime']//100

r['DepTime'] = r.apply(func, axis=1)

In [0]:
l=['ATL','CLT','DEN','DFW','EWR','IAH','JFK','LAS','LAX','MCO','MIA','ORD','PHX','SEA','SFO']
t = pd.DataFrame()
for apt in l:
  temp = r[r.Origin == apt]
  t = pd.concat([t,temp],axis = 0)

In [0]:
t2 =t.loc[t['Dest'].isin(l)]

In [0]:
t2

In [0]:
import os
f=0
needed = ['2016-1.json',
          '2016-2.json',
          '2016-3.json',
          '2016-4.json',
          '2016-5.json',
          '2016-6.json',
          '2016-7.json',
          '2016-8.json',
          '2016-9.json',
          '2016-10.json',
          '2016-11.json',
          '2016-12.json',
          '2017-1.json',
          '2017-2.json',
          '2017-3.json',
          '2017-4.json',
          '2017-5.json',
          '2017-6.json',
          '2017-7.json',
          '2017-8.json',
          '2017-9.json',
          '2017-10.json',
          '2017-11.json',
          '2017-12.json']
w=pd.DataFrame()
m=1
for i in os.listdir('/content/gdrive/My Drive/ML/weather') :
  currdir = '/content/gdrive/My Drive/ML/weather/'+i
  temp=pd.DataFrame()
  for j in needed:
    filename = '/content/gdrive/My Drive/ML/weather/'+i+'/'+j
    w1= pd.read_json(filename)
    day_cnt=1
    for p in range(len(w1['data']['weather'])):
      day = pd.DataFrame()
      for h in range(24):
        d=pd.DataFrame(w1['data']['weather'][p]['hourly'][h])
        d['DepTime']=h
        d['Month']=(j.split('-'))[1].split('.')[0]
        d['year']=(j.split('-'))[0]
        d['DayofMonth']=day_cnt
        day=pd.concat([day,d],axis=0,ignore_index=True)
      temp=pd.concat([temp,day],axis=0,ignore_index=True)
      day_cnt+=1
  temp['Origin']=i    
  w=pd.concat([w,temp],axis=0,ignore_index=True)
  print(i+' '+j)
  print(w.shape)

In [0]:
w.to_csv('/content/gdrive/My Drive/ML/weatherDataset.csv', sep='\t', encoding='utf-8')

In [0]:
t2.to_csv('/content/gdrive/My Drive/ML/flightDataset.csv', sep='\t', encoding='utf-8')

In [0]:
--------------

,Quarter,Month,DayofMonth,DayOfWeek,FlightNum,OriginAirportID,Origin,DestAirportID,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,CRSArrTime,ArrTime,year
3510,1,1,1,5,139,10397,ATL,13303,810,808.0,-2.0,0.0,1016,1001.0,2016
3511,1,1,2,6,139,10397,ATL,13303,810,812.0,2.0,2.0,1016,1002.0,2016
3512,1,1,3,7,139,10397,ATL,13303,810,807.0,-3.0,0.0,1016,1006.0,2016
3513,1,1,4,1,139,10397,ATL,13303,810,825.0,15.0,15.0,1016,1010.0,2016
3514,1,1,5,2,139,10397,ATL,13303,810,805.0,-5.0,0.0,1010,1033.0,2016
3515,1,1,12,2,139,10397,ATL,13303,810,806.0,-4.0,0.0,1010,1035.0,2016
3516,1,1,13,3,139,10397,ATL,13303,810,806.0,-4.0,0.0,1010,1010.0,2016
3517,1,1,14,4,139,10397,ATL,13303,810,818.0,8.0,8.0,1010,1019.0,2016
3518,1,1,15,5,139,10397,ATL,13303,810,823.0,13.0,13.0,1010,1027.0,2016
3519,1,1,16,6,139,10397,ATL,13303,810,1033.0,143.0,143.0,1010,1347.0,2016
3520,1,1,17,7,139,10397,ATL,13303,810,807.0,-3.0,0.0,1010,1008.0,2016
3521,1,1,18,1,139,10397,ATL,13303,810,816.0,6.0,6.0,1010,1023.0,2016
3522,1,1,19,2,139,10397,ATL,13303,810,806.0,-4.0,0.0,1010,1001.0,2016
3523,1,1,20,3,139,10397,ATL,13303,810,2231.0,861.0,861.0,1010,18.0,2016
3524,1,1,21,4,139,10397,ATL,13303,810,805.0,-5.0,0.0,1010,952.0,2016
3525,1,1,22,5,139,10397,ATL,13303,810,809.0,-1.0,0.0,1010,1051.0,2016
3526,1,1,23,6,139,10397,ATL,13303,810,814.0,4.0,4.0,1010,1018.0,2016
3527,1,1,24,7,139,10397,ATL,13303,810,809.0,-1.0,0.0,1010,959.0,2016
3528,1,1,25,1,139,10397,ATL,13303,810,823.0,13.0,13.0,1010,1011.0,2016
3529,1,1,26,2,139,10397,ATL,13303,810,806.0,-4.0,0.0,1010,957.0,2016
3530,1,1,27,3,139,10397,ATL,13303,810,804.0,-6.0,0.0,1010,1008.0,2016
3531,1,1,28,4,139,10397,ATL,13303,810,809.0,-1.0,0.0,1010,1040.0,2016
3532,1,1,29,5,139,10397,ATL,13303,810,809.0,-1.0,0.0,1010,1036.0,2016
3533,1,1,30,6,139,10397,ATL,13303,810,817.0,7.0,7.0,1010,1023.0,2016
3534,1,1,31,7,139,10397,ATL,13303,810,809.0,-1.0,0.0,1010,1000.0,2016
7006,1,1,1,5,349,10397,ATL,11298,915,910.0,-5.0,0.0,1047,1039.0,2016
7007,1,1,2,6,349,10397,ATL,11298,915,1025.0,70.0,70.0,1047,1148.0,2016
7008,1,1,3,7,349,10397,ATL,11298,915,913.0,-2.0,0.0,1047,1054.0,2016
7009,1,1,4,1,349,10397,ATL,11298,915,913.0,-2.0,0.0,1047,1039.0,2016
8264,1,1,1,5,232,10397,ATL,11298,1921,1950.0,29.0,29.0,2056,2106.0,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11291989,4,12,17,7,1799,14771,SFO,11618,2115,2108.0,-7.0,0.0,537,519.0,2017
11291990,4,12,17,7,1800,14771,SFO,13930,1827,1820.0,-7.0,0.0,29,20.0,2017
11292006,4,12,17,7,1820,14771,SFO,12892,1205,1203.0,-2.0,0.0,1344,1338.0,2017
11292014,4,12,17,7,1830,14771,SFO,10693,1055,1112.0,17.0,17.0,1714,1729.0,2017
11292016,4,12,17,7,1833,14771,SFO,11298,820,816.0,-4.0,0.0,1354,1352.0,2017
11292026,4,12,17,7,1845,14771,SFO,11292,1555,1602.0,7.0,7.0,1925,1929.0,2017
11292039,4,12,17,7,1858,14771,SFO,11292,1320,1337.0,17.0,17.0,1647,1710.0,2017
11292044,4,12,17,7,1865,14771,SFO,10721,1110,1215.0,65.0,65.0,1941,2032.0,2017
11292057,4,12,17,7,1878,14771,SFO,12266,1554,1548.0,-6.0,0.0,2141,2138.0,2017
11292067,4,12,17,7,1889,14771,SFO,10423,2000,1953.0,-7.0,0.0,127,122.0,2017
11292072,4,12,17,7,1893,14771,SFO,11292,1931,1927.0,-4.0,0.0,2258,2256.0,2017
11292080,4,12,17,7,1900,14771,SFO,14679,1056,1051.0,-5.0,0.0,1234,1223.0,2017
11292082,4,12,17,7,1906,14771,SFO,14679,1400,1354.0,-6.0,0.0,1534,1515.0,2017
11292085,4,12,17,7,1912,14771,SFO,12892,932,926.0,-6.0,0.0,1115,1045.0,2017
11292092,4,12,17,7,1919,14771,SFO,14262,1030,1026.0,-4.0,0.0,1209,1149.0,2017
11292116,4,12,17,7,1948,14771,SFO,14747,1510,1515.0,5.0,5.0,1723,1728.0,2017
11292118,4,12,17,7,1950,14771,SFO,11042,1258,1256.0,-2.0,0.0,2032,2035.0,2017
11292125,4,12,17,7,1958,14771,SFO,12266,925,941.0,16.0,16.0,1518,1532.0,2017
11292160,4,12,17,7,1994,14771,SFO,12892,1258,1257.0,-1.0,0.0,1431,1426.0,2017
11292191,4,12,17,7,2031,14771,SFO,11292,1802,1757.0,-5.0,0.0,2134,2133.0,2017
11292204,4,12,17,7,2044,14771,SFO,11618,1515,1512.0,-3.0,0.0,2327,2313.0,2017
11292206,4,12,17,7,2046,14771,SFO,11278,1309,1316.0,7.0,7.0,2105,2124.0,2017
11292217,4,12,17,7,2055,14771,SFO,14057,1245,1308.0,23.0,23.0,1435,1452.0,2017
11292218,4,12,17,7,2056,14771,SFO,13264,1845,1836.0,-9.0,0.0,2006,1950.0,2017
11292219,4,12,17,7,2058,14771,SFO,12266,1814,1808.0,-6.0,0.0,1,2356.0,2017
11292221,4,12,17,7,2060,14771,SFO,10693,2250,2244.0,-6.0,0.0,508,511.0,2017
11292224,4,12,17,7,2063,14771,SFO,10821,930,926.0,-4.0,0.0,1745,1722.0,2017
11292225,4,12,17,7,2064,14771,SFO,14100,840,834.0,-6.0,0.0,1659,1646.0,2017
11292230,4,12,17,7,2070,14771,SFO,12339,1640,1636.0,-4.0,0.0,2350,2347.0,2017
11292237,4,12,17,7,2081,14771,SFO,14893,2322,2315.0,-7.0,0.0,15,9.0,2017